---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-klap-genesary-github-com-v1alpha1-entry
  failurePolicy: Fail
  name: mentry-v1alpha1.kb.io
  rules:
  - apiGroups:
    - klap.genesary.github.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - entries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-klap-genesary-github-com-v1alpha1-server
  failurePolicy: Fail
  name: mserver-v1alpha1.kb.io
  rules:
  - apiGroups:
    - klap.genesary.github.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-klap-genesary-github-com-v1alpha1-entry
  failurePolicy: Fail
  name: ventry-v1alpha1.kb.io
  rules:
  - apiGroups:
    - klap.genesary.github.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - entries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-klap-genesary-github-com-v1alpha1-server
  failurePolicy: Fail
  name: vserver-v1alpha1.kb.io
  rules:
  - apiGroups:
    - klap.genesary.github.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servers
  sideEffects: None
