---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - klap.genesary.github.com
  resources:
  - entries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klap.genesary.github.com
  resources:
  - entries/finalizers
  verbs:
  - update
- apiGroups:
  - klap.genesary.github.com
  resources:
  - entries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - klap.genesary.github.com
  resources:
  - servers
  verbs:
  - get
  - list
  - watch
