apiVersion: klap.genesary.github.com/v1alpha1
kind: Entry
metadata:
  labels:
    app.kubernetes.io/name: klap
    app.kubernetes.io/managed-by: kustomize
  name: entry-sample
  namespace: default
spec:
  dn: cn=joe,dc=example,dc=org
  prune: true
  force: false
  attributes:
    objectClass:
      - inetOrgPerson
    sn:
      - Doe
    mail:
      - joe@example.org
    description:
      - "Imported by klap"
  serverRef:
    name: server-sample
    namespace: openldap
  