apiVersion: klap.genesary.github.com/v1alpha1
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: klap
    app.kubernetes.io/managed-by: kustomize
  name: server-sample
  namespace: openldap
spec:
  url: ldap://ldap.openldap.svc.cluster.local
  baseDN: dc=example,dc=org
  bindDN: cn=admin,dc=example,dc=org
  startTLS: true
  passwordSecretRef:
    name: openldap-passwd
    key: adminPassword
  tlsSecretRef:
    name: openldap-server-cert
  allowedNamespaces:
    namePattern: default
